namespace NameGenerator;
internal class Writers
{
    public static string[] WritersWithNobel =
    {
        "Sully Prudhomme",
"Theodor Mommsen",
"Bjørnstjerne Bjørnson",
"Frédéric Mistral",
"José Echegaray y Eizaguirre",
"Henryk Sienkiewicz",
"Giosuè Carducci",
"Rudyard Kipling",
"Rudolf Christoph Eucken",
"Selma Lagerlöf",
"Paul Heyse",
"Count Maurice Maeterlinck",
"Gerhart Hauptmann",
"Rabindranath Tagore",
"Romain Rolland",
"Verner von Heidenstam",
"Karl Adolph Gjellerup",
"Henrik Pontoppidan",
"Carl Spitteler",
"Knut Hamsun",
"Anatole France",
"Jacinto Benavente",
"William Butler Yeats",
"Władysław Reymont",
"George Bernard Shaw",
"Grazia Deledda",
"Henri Bergson",
"Sigrid Undset",
"Thomas Mann",
"Sinclair Lewis",
"Erik Axel Karlfeldt",
"John Galsworthy",
"Ivan Alekseyevich Bunin",
"Luigi Pirandello",
"Eugene O'Neill",
"Roger Martin du Gard",
"Pearl S. Buck",
"Frans Eemil Sillanpää",
"Johannes Vilhelm Jensen",
"Gabriela Mistral",
"Hermann Hesse",
"André Gide",
"T. S. Eliot",
"William Faulkner",
"Bertrand Russell",
"Pär Lagerkvist",
"François Mauriac",
"Sir Winston Churchill",
"Ernest Hemingway",
"Halldór Laxness",
"Juan Ramón Jiménez",
"Albert Camus",
"Boris Pasternak",
"Salvatore Quasimodo",
"Saint-John Perse",
"Ivo Andric",
"John Steinbeck",
"Giorgos Seferis",
"Jean-Paul Sartre",
"Michail Sholokhov",
"Shmuel Yosef Agnon",
"Nelly Sachs",
"Miguel Ángel Asturias",
"Yasunari Kawabata",
"Samuel Beckett",
"Aleksandr Solzhenitsyn",
"Pablo Neruda",
"Heinrich Böll",
"Patrick White",
"Eyvind Johnson",
"Harry Martinson",
"Eugenio Montale",
"Saul Bellow",
"Vicente Aleixandre",
"Isaac Bashevis Singer",
"Odysseas Elytis",
"Czesław Miłosz",
"Elias Canetti",
"Gabriel García Márquez",
"William Golding",
"Jaroslav Seifert",
"Claude Simon",
"Akinwande Oluwole Soyinka",
"Joseph Brodsky",
"Naguib Mahfouz",
"Camilo José Cela",
"Octavio Paz",
"Nadine Gordimer",
"Derek Walcott",
"Toni Morrison",
"Kenzaburo Oe",
"Seamus Heaney",
"Wisława Szymborska",
"Dario Fo",
"José Saramago",
"Günter Grass",
"Gao Xingjian",
"Vidiadhar Surajprasad Naipaul",
"Imre Kertész",
"John Maxwell Coetzee",
"Elfriede Jelinek",
"Harold Pinter",
"Orhan Pamuk",
"Doris Lessing",
"J. M. G. Le Clézio",
"Herta Müller",
"Mario Vargas Llosa",
"Tomas Tranströmer",
"Mo Yan",
"Alice Munro",
"Patrick Modiano",
"Svetlana Alexievich",
"Bob Dylan",
"Kazuo Ishiguro",
"Olga Tokarczuk",
"Peter Handke",
"Louise Glück",
"Abdulrazak Gurnah",
"Annie Ernaux",
"Jon Fosse",
    };
}
