name: .NET build

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run:  |
        cd src
        cd NameGenerator
        dotnet restore
        dotnet build
    - name: Build
      run: |
        cd src
        cd NameGenerator
        dotnet tool restore
        dotnet r pack

    - name: 'Upload package'
      if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      uses: actions/upload-artifact@v4
      with:
        name: data_${{github.run_number}}
        path: src/NameGenerator/PACK/*symbols.nupkg
        retention-days: 1        
    
    - name: push nuget
      if: startsWith(github.ref, 'refs/tags/v') # This line ensures the step runs only if a tag version is present
      run: |
          dotnet nuget push ${{github.workspace}}/src/NameGenerator/PACK/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
